# Etapa 1: Build de Angular
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration=production

# Etapa 2: Producción con Nginx
FROM nginx:alpine
COPY --from=build /app/dist/cordobacelulares /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
