FROM node:20

# Establece el directorio de trabajo en la raíz del proyecto
WORKDIR /app

# Copia los archivos de configuración
COPY package*.json ./
RUN npm install

# Copia todo el resto del código
COPY . .

# Construye la aplicación Angular
RUN npm run build -- --configuration=production

# Etapa de producción (Nginx)
FROM nginx:alpine
COPY --from=build /app/dist/cordobacelulares /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
