# Etapa 1: Build de Angular
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration=production

# Etapa 2: Producción con Nginx
FROM nginx:alpine

# Reemplaza la config default por una con SPA fallback
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Limpiar html default (bien)
RUN rm -rf /usr/share/nginx/html/*

# Copiar el build real (en tu caso está en /browser)
COPY --from=build /app/dist/cordobacelulares/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
